name: rock-dev-env

services:
  rock:
    image: localhost/rockrms:latest
    container_name: rock
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${ROCK_HTTP_PORT}:80"
      - "${ROCK_HTTPS_PORT}:443"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=sa
      - DB_PASSWORD=${SQL_SA_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
